# Generated by Django 6.0.1 on 2026-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experement',
            name='frames',
            field=models.ManyToManyField(related_name='experements', to='part_1.frame'),
        ),
    ]
